### PR TITLE
Update trotter.html

### PR DESCRIPTION
**Pull request by alxnorden**
Added example case for testing functionality, for beginners.

### CODE REVIEW

**Comment by pnathan** [comment]
Hi! 

this looks good. I will take a swing at this in the next couple days. I should get CD running for this repo!

**Comment by alxnorden** [comment]
Cool! And thank You for Your work!

**Comment by alxnorden** [comment]
Is it of value to the project if other usability changes are suggested? Understanding You might have other commitments...

**Comment by pnathan** [comment]
Yes. You can open this PR! I just have to remember where I put my deploy scripts!

**Pull request closed without merging**
